bearhack-ucr/bearhack2024

src/components/static/GetInvolved.jsx
src/components/static/HorizontalLine.jsx

closes #24
extract horizontal line to a separate component
No

extract horizontal line

---

src/components/static/Team.jsx
src/components/static/TeamMember.jsx
src/components/static/Title.jsx
src/data/static/TeamMembers.js

Meet the Team

---

src/app/layout.js
src/components/dynamic/Error.jsx
src/components/dynamic/Input.jsx
src/components/dynamic/Loading.jsx
src/components/dynamic/Radio.jsx
src/components/dynamic/Select.jsx
src/components/dynamic/form/Form.jsx
src/components/dynamic/form/Questions.jsx
src/components/dynamic/form/Textarea.jsx
src/components/dynamic/form/Upload.jsx
src/components/static/AboutUs.jsx
src/components/static/FAQ.jsx
src/components/static/Footer.jsx
src/components/static/GetInvolved.jsx
src/components/static/Link.jsx
src/components/static/Team.jsx
src/components/static/Title.jsx
tailwind.config.js

fixed asterisk forms, fixed fonts, loading page, 404 page, some bugs

---

.github/workflows/pull-request.yaml
.github/workflows/sync-template.yaml
src/app/error.js
src/app/layout.js
src/app/page.js
src/components/dynamic/Checkbox.jsx
src/components/dynamic/Error.jsx
src/components/dynamic/Loading.jsx
src/components/dynamic/Radio.jsx
src/components/dynamic/Session.jsx
src/components/dynamic/admin/dashboards/Toolbar.jsx
src/components/dynamic/admin/services/Toolbar.jsx
src/components/dynamic/form/Form.jsx
src/components/dynamic/form/Textarea.jsx
src/components/dynamic/form/Upload.jsx
src/components/static/Countdown.jsx
src/components/static/Navbar.jsx
src/components/static/live/Live.jsx
src/components/static/postlive/Postlive.jsx
src/components/static/prelive/Prelive.jsx
src/data/Releases.js
src/data/dynamic/admin/Mentors.js
src/data/dynamic/admin/Volunteers.js
src/data/dynamic/form/Information.js
src/utils/error.js

finish up landing details

---

src/components/static/Countdown.jsx
src/components/static/Title.jsx
src/data/Config.js

fixes #43 
fixes title & countdown responsiveness issues
change countdown to DD HH MM SS format

Responsiveness

---

src/app/layout.js
src/components/dynamic/ProtectedPage.jsx
src/components/static/AboutUs.jsx
src/components/static/FAQ.jsx
src/components/static/Footer.jsx
src/components/static/GetInvolved.jsx
src/components/static/Team.jsx
src/components/static/Title.jsx
src/components/static/ToggleSelection.jsx

https://github.com/bearhack-ucr/bearhack2024/assets/91511317/9d2ba9e2-6e5f-4173-8a8c-ccf1899f4314

responsiveness, status bar

---

src/components/dynamic/Checkbox.jsx
src/components/dynamic/Select.jsx

fix #75 
fix #76 -- should i go back to darker color? i think lighter color looks just as good

fix Select textarea transparency and checkbox spacing bug

---

src/components/static/Butterfly.jsx
src/components/static/GetInvolved.jsx
src/components/static/Member.jsx
src/components/static/Team.jsx
src/components/static/Title.jsx

fix #71 -- moves the butterfly to the side of the "BEARHACK 2024" title
and various styling overflow bug fixes

landing cleanup

---

src/app/form/[type]/page.js
src/components/dynamic/Checkbox.jsx
src/components/dynamic/user/CheckIn.jsx
src/components/dynamic/user/Header.jsx
src/components/dynamic/user/Team.jsx
src/components/dynamic/user/User.jsx

Reverts bearhack-ucr/bearhack2024#54
popping this off to fix the bad revert merge

Revert "styled user Dashboard"

---

src/components/static/Title.jsx

Shooting Stars Point Downward

---

src/components/static/Tracks.jsx
tailwind.config.js

I didn't add a screenshot since i was suppose to add an animation

chagned key frames and added animate bounce to the tracks

---

package-lock.json
src/components/dynamic/Select.jsx
tailwind.config.js

changed dropdown colors

---

src/components/Team.jsx
src/components/schedule/Events.jsx

Nova sagittarii/center grid

---

src/components/Team.jsx

fix team alignment again

---

src/components/Navigation.jsx

moved nav items to top

---

src/components/user/Collapse.jsx
src/components/user/Dashboard.jsx
src/components/user/Packing.jsx
src/components/user/Rooms.jsx

changed the font colors on the user dashboard

---

src/components/admin/services/checkin/CheckIn.jsx

Fix max width to delete scroll bar

---

src/components/Select.jsx

fix select text black on black

---

package-lock.json
package.json
src/components/AboutUs.jsx
src/components/AboutUsText.jsx
src/components/GetInvolved.jsx
src/components/Title.jsx
src/components/Tracks.jsx
src/components/schedule/Events.jsx
tailwind.config.js

Nova sagittarii/landing

---

src/components/Checkbox.jsx
src/data/admin/Admins.js
src/data/admin/Committees.js
src/data/admin/Leads.js
src/data/admin/Participants.js

Admin dashboard text visibility
